-- V1__create_cards_enums.sql
-- Create ENUMs for card module
CREATE TYPE CARD_TYPE AS ENUM (
    'DEBIT',
    'CREDIT',
    'PREPAID'
);

CREATE TYPE CARD_STATUS AS ENUM (
    'ACTIVE',
    'BLOCKED',
    'EXPIRED',
    'CANCELLED'
);

CREATE TYPE VIRTUAL_CARD_STATUS AS ENUM (
    'ACTIVE',
    'SUSPENDED',
    'CANCELLED'
);

CREATE TYPE TRANSACTION_TYPE AS ENUM (
    'PURCHASE',
    'WITHDRAWAL',
    'PAYMENT',
    'FEE',
    'REFUND'
);

CREATE TYPE TRANSACTION_STATUS AS ENUM (
    'PENDING',
    'COMPLETED',
    'FAILED',
    'REVERSED'
);

CREATE TYPE LIMIT_TYPE AS ENUM (
    'DAILY_SPENDING',
    'MONTHLY_SPENDING',
    'ATM_WITHDRAWAL',
    'ONLINE_PURCHASE'
);

CREATE TYPE RESET_PERIOD AS ENUM (
    'DAILY',
    'MONTHLY'
);

CREATE TYPE CONFIG_TYPE AS ENUM (
    'CONTACTLESS_ENABLED',
    'CHIP_ENABLED',
    'ONLINE_TRANSACTIONS_ENABLED',
    'INTERNATIONAL_USAGE_ENABLED'
);

CREATE TYPE SECURITY_FEATURE AS ENUM (
    'PIN_ENABLED',
    'TWO_FACTOR_AUTH',
    'FRAUD_DETECTION_ENABLED'
);

CREATE TYPE PROVIDER_STATUS AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'PENDING',
    'SUSPENDED'
);